version: '3.8'

services:
  zabbix-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix12345
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/:rw

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.4-latest
    hostname: zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix12345
      - ZBX_SRV_HOST=zabbix-server
    ports:
      - "10051:10051"
    links:
      - zabbix-db

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.4-latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix12345
    ports:
      - "443:8443"
      - "80:8080"
    links:
      - zabbix-db
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-5.4-latest
    hostname: "zabbix-agent"
    environment:
      - ZBX_SRV_HOST=zabbix-server
    links:
      - zabbix-server

volumes:
  db-data:
